### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by mcepl** [lewis6991/spellsitter.nvim#1]
Ehm, a stupid question … when I install spellsitter, how to I make it to work. Installed per README, add 
```vim
if has("nvim-0.5.0")

lua << EOS
require'nvim-treesitter.configs'.setup {
  -- one of "all", "language", or a list of languages
  ensure_installed = "all",
  highlight = {
    enable = true
  },
  indent = {
    enable = true
  },
}

require('spellsitter').setup{}
EOS

set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()

endif
```
as ``~/.vim/plugin/nvim-treesitter.vim``, started neovim with rST document, and now what?

Should I `set spell`?

**Comment by lewis6991** [comment]
You also need hunspell installed, I just added some details to the README.

**Comment by lewis6991** [comment]
No need for `set spell` if anything `set nospell` would be better.

**Comment by mcepl** [comment]
> You also need hunspell installed, I just added some details to the README.

Of course,
```bash
~@stitny$ echo enterperuner | hunspell -a -d en_GB
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.7.0)
& enterperuner 3 0: interpenetrate, triterpene, serpentine

~@stitny$ echo babika | hunspell -m -d cs_CZ
babika

~@stitny$ echo babička | hunspell -m -d cs_CZ
babička  st:babička

~@stitny$
```

**Comment by lewis6991** [comment]
Maybe add `-d cs_CZ` to `hunspell_args` in setup

**Comment by lewis6991** [comment]
Also spellsitter is only setup to check comments by default. To change this alter the `capture` setting.

Maybe try and different file type for the time being.

**Comment by lewis6991** [comment]
Thinking about it, given your use case, it might be useful to provide a way to disable the treesitter aspect since you probably want all code in an rst file to be spellchecked.

**Comment by mcepl** [comment]
> Thinking about it, given your use case, it might be useful to provide a way to disable the treesitter aspect since you probably want all code in an rst file to be spellchecked.

Yup.

**Comment by lewis6991** [comment]
This should help: https://github.com/lewis6991/spellsitter.nvim/commit/a43903c9688301c2681010c33e20f33fb19b48fc

In spellsitters setup just set `captures = {}` to enable spellchecking all text.

**Comment by mcepl** [comment]
Also, how do you set spelling language? It seems to take language settings from locale, but that's horribly insufficient. I am Czech, have locale `cs_CZ.UTF-8`, but of course a lot of texts (perhaps, even most) are in `en_GB.UTF-8`.

**Comment by lewis6991** [comment]
For now you need to use `hunspell_args` in spellsitter setup to specify the dictionary you want to use.

**Comment by mcepl** [comment]
OK, progress:
![Uploading screenshot-2021-02-25_00-02-1614208717.png…]()

With changed locale I get this.

Two problems:

1. Obviously, settings must be specific for different documents of types (I really don't want to spellcheck Python code)

2. It seems to me that there is something wrong with parsing of results (“So, Hermione …” sentence has highliting shifted by character).

**Comment by lewis6991** [comment]
Looks like some bugs I need to squash.

I need to add more config on file types, much like how nvim-treesitter does it.

Did `hunspell_args` not work? Remember each argument needs to be an entry in the table so something like:

`hunspell_args = {'-d', 'en_GB'}`

**Comment by lewis6991** [comment]
Looks like the first character is being treated weirdly. Changing it to `"` fixes it. I think this is a Neovim issue as hunspell reports the correct offset of 5, however passing that as the column to `nvim_buf_set_extmark` causes it to be placed on the wrong column.

<img width="541" alt="Screenshot 2021-02-24 at 23 38 52" src="https://user-images.githubusercontent.com/7904185/109081012-7661fe80-76f9-11eb-84da-f25c6e849d1a.png">

**Comment by mcepl** [comment]
> Looks like some bugs I need to squash.

Bytes v Unicode characters? “ (U+201C) is of course English open doublequote and perfectly legal character.

Hmm, tried ``hunspell_args = {'-i', 'utf-8', '-d', 'en_GB'},`` (although it should be unnecessary my locale is UTF-8 already), but nothing changed.

> Did `hunspell_args` not work? Remember each argument needs to be an entry in the table so something like:
> 
> `hunspell_args = {'-d', 'en_GB'}`

Works perfectly.

**Comment by lewis6991** [comment]
Raised neovim issue: https://github.com/neovim/neovim/issues/14010

**Comment by bfredl** [comment]
https://github.com/hunspell/hunspell/blob/8a2fdfe5a6bb1cbafc04b0c8486abcefd17ad903/src/tools/hunspell.cxx#L923 seems hunspell actively converts byte indices to UTF-32 indices _even_ in explicit UTF-8 mode which is a bit unfortunate but possible to work around (use `vim.str_byteindex` from lua).

**Comment by mcepl** [comment]
OK, that’s silly, but at least there seems to be a way how to deal with it. Thank you.

**Comment by lewis6991** [comment]
Thanks @bfredl. I've applied `vim.str_byteindex` to master and appears to work well.

@mcepl give master a spin and let me know if things have improved.

**Comment by mcepl** [comment]
Works, lovely. Let me remove https://github.com/mcepl/nvim-spellcheck :)

So, now what remains is:

  * [ ] make spellchecker enabled/disabled per `filetype` (or change `captures` accordingly, including an option which would switch off spellchecking completely)
  * [ ] make some way how to change language of spellchecking (couldn’t we use ``spelllang`` even when ``nospell``?)
  * [ ] add the current word to the personal dictionary for the current language
  * [ ] suggest fix for the current misspelled word

Do I miss anything?

(optional, make the plugin work with another backends … nuspell, aspell, enchant-2?)

**Comment by matu3ba** [comment]
> Do I miss anything?
> 
> (optional, make the plugin work with another backends … nuspell, aspell, enchant-2?)

more of follow-up work: telescope picker, descriptions how to integrate into project-specific setup: I like [telescope-project](https://github.com/nvim-telescope/telescope-project.nvim), but its quite WIP.

**Comment by mcepl** [comment]
Yes, these would be nice, but those I wrote are (at least from my point of view) the minimal functionality required for me to switch from the internal speller to this plugin (which I would LOVE TO do).

**Comment by matu3ba** [comment]
@mcepl The plugin does not support spell suggestions (yet).

**Comment by mcepl** [comment]
Closing before this turns into complete “chatting in the pub about everything” mess.
