### ISSUE TITLE
Multi-line C style comments don't show all misspelled words.

### ISSUE THREAD

**Issue by tllilleh** [lewis6991/spellsitter.nvim#17]
With multi-line C style comments only misspelled words on the line with the closing comment sequence (`*/`) are shown.

For example, in this comment:
```
/* line one: qwer
  * line two: asdf
  * line three: zxcv */
```
  
 Only "zxcv" will be shown as being misspelled.

**Comment by lewis6991** [comment]
Fixed with #18
