### ISSUE TITLE
error: index out of range and performance problem(s)

### ISSUE THREAD

**Issue by matu3ba** [lewis6991/spellsitter.nvim#2]
1. When typing in a file with bigger amount of comments, ie plugin file for packer, I get:
`spellsitter: Error executing lua: ...e/pack/packer/start/spellsitter.nvim/lua/spellsitter.lua:34: index out of range`

2. The other problem(s) could be somewhat related to the unresolved performance problem in rainbow:
https://github.com/p00f/nvim-ts-rainbow/issues/5

3. The spellcheck somehow gets reapplied to words on other lines (the spell errors are redrawn with underlining them).

**There dont show up treesitter problems.**

**Comment by matu3ba** [comment]
Hint: The approach to solve the performance problem should be quite identical as [here](https://github.com/p00f/nvim-ts-rainbow/issues/5#issuecomment-797794027).

I think getting recently pressed buttons + textchanges of the current line in lua should be even part of neovim for proper treesitter support.

**Comment by lewis6991** [comment]
This is not something I've ever observed since hunspell was replaced with the built in spellchecker. Is this still a problem or can this issue be closed?

**Comment by matu3ba** [comment]
Ah, wasnt checking lately again. 

@lewis6991 So the plan is to get the inbuild properly running (and eventually use hunspell inside neovim core) ?
Would be nice to write the roadmap somewhere including that it overwrites the spellcheck behavior.

Probably you could also make a list of stuff (options, keybindings etc) that the inbuild spellchecker can do and how to deviate/optimize it?

**Comment by matu3ba** [comment]
Closing, cause it was fixed.

**Comment by lewis6991** [comment]
> @lewis6991 So the plan is to get the inbuild properly running (and eventually use hunspell inside neovim core) ?
Would be nice to write the roadmap somewhere including that it overwrites the spellcheck behavior.

There isn't really a plan as such. The only motivation of this project was to get some spellchecking working for treesitter enabled buffers. General improvements to neovim's spellchecker are a bit out of scope unless they are absolutely necessary to get functionality to work.

> Probably you could also make a list of stuff (options, keybindings etc) that the inbuild spellchecker can do and how to deviate/optimize it?

The goal is for this plugin to be pretty minimal. So far pretty much all the keybindings work. Specifically:
```
    'z=', 'zW', 'zg', 'zG', 'zw', 'zuW', 'zug', 'zuG', 'zuw'
```

You can find out what these do with `:help spell`.

One thing that isn't implemented yet is `[s` and `]s` which needs a custom implementation.
