### ISSUE TITLE
Ignore words

### ISSUE THREAD

**Issue by bellini666** [lewis6991/spellsitter.nvim#29]
Would it be possible to define a list of ignored words, maybe per filetype?

E.g. In python I have some `# noqa: SOMECOME` to disable a specific linter in the line, which are not proper words

**Comment by e2oneedh2o** [comment]
It is possible; try <kbd>z</kbd><kbd>g</kbd>
[You can read more here](https://vimtricks.com/p/vimtrick-spell-checking-in-vim/) or use vim's help feature

**Comment by lewis6991** [comment]
@e2oneedh2o  should be the accepted answer.
