### ISSUE TITLE
Conflict with Packer

### ISSUE THREAD

**Issue by 1478zhcy** [lewis6991/spellsitter.nvim#34]
If I use this plugin and I use PackerClean to remove the plugin which not in my plugin list, the pop-up window that Packer prompts whether to confirm the removed plug-in list will disappear, which is very strange.

**Comment by 1478zhcy** [comment]
In addition, my neovim is the latest version compiled a few hours ago. I initially thought it might be the 0.6 version of neovim that caused this problem.

**Comment by lewis6991** [comment]
Sorry I don't understand. Can you explain more?

**Comment by 1478zhcy** [comment]
Under normal circumstances, if I delete a plug-in in `plugins.lua` and then run `PakcerSync` or `PackerClean`, there will be a dialog box prompting me whether to remove this or these plug-ins. Like in the picture
![image](https://user-images.githubusercontent.com/61115159/140326314-dfab2c0a-986f-41b2-b933-759b9c543bb2.png)
But after I used spellsitter (or after running `require('spellsitter').setup()`), this prompt box disappeared
![image](https://user-images.githubusercontent.com/61115159/140325859-39e354c1-71fc-4021-94a7-a6a8890c96e3.png)
The output of `nvim --version` is
```
NVIM v0.6.0-dev+555-gf26b39131
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by lewis6991** [comment]
I can reproduce the issue without spellsitter with:

```viml
autocmd BufNew * lua vim.schedule(function() end)    
```

So this is either an issue with Packer or Neovim.

**Comment by lewis6991** [comment]
Haven't really got time to report this as an issue on either project but will close here.

**Comment by lewis6991** [comment]
4de1700287394196d15276e53de8443f843e5da6 will avoid the issue for now.
