### ISSUE TITLE
SpellSitter saying spell checking is not possible 

### ISSUE THREAD

**Issue by DarkenedOrigins** [lewis6991/spellsitter.nvim#35]
I am using neovim 5.1
I have treesitter installed
I am editing a markdown file
I misspelled a word too see if the plug in was work it didn't highlight it so I did
:spellinfo
The output was
E756: spell checking is not possible

My setup is the basic packer setup with the config inside the use

**Comment by lewis6991** [comment]
Do you have a parser for Markdown installed?

**Comment by DarkenedOrigins** [comment]
No, I tried TSinstall markdown / md and it does not seem to be available. I checked on the main site and it seems treesitter does not support md built in. Do you have any suggestions for a markdown parser? If not you can mark this issue as resolved
