### ISSUE TITLE
amsmath latex math environments

### ISSUE THREAD

**Issue by yashamon** [lewis6991/spellsitter.nvim#37]
Thanks for the fantastic plugin. The plugin already recognizes inline and display math environments like \\[ \\]
However there are amsmath extensions, used by all scientific papers, most significant being:
\begin{equation} 
\end {equation}
Further documented here: http://www.ams.org/arc/tex/amsmath/amsldoc.pdf. Assuming that treesitter already knows how to parse them. Which seems to be the case as far as syntax highlighting is concerned. Could these also be supported?

**Comment by lewis6991** [comment]
You'll have to help me out a bit because I don't use latex.

Give me an example of some latex code with which parts you want highlighting?

This is really just a simple case of tweaking the queries. You can install https://github.com/nvim-treesitter/playground and run `:TSPlaygroundToggle` to see the parse tree.

**Comment by yashamon** [comment]
I will check out playground. How would I go about adding queries? I am a noob at this.

The basic example is 
\begin{equation} \label(somelabel)
e^{\pi} = -1
\end{equation}
the main difference with \[ \] is that the equation will have a label. The label itself is optional.

**Comment by lewis6991** [comment]
The above snippet is parsed by tree-sitter as:

```
environment [1, 0] - [3, 14]
  begin: begin [1, 0] - [1, 16]
    name: word [1, 7] - [1, 15]
  ERROR [1, 17] - [1, 23]
  child: mixed_group [1, 23] - [1, 34]
    child: text [1, 24] - [1, 33]
      word [1, 24] - [1, 33]
  child: text [2, 0] - [2, 2]
    word [2, 0] - [2, 2]
  child: brace_group [2, 2] - [2, 7]
    child: generic_command [2, 3] - [2, 6]
      name: generic_command_name [2, 3] - [2, 6]
  child: text [2, 8] - [2, 12]
    word [2, 10] - [2, 12]
  end: end [3, 0] - [3, 14]
    name: word [3, 5] - [3, 13]
```

Which has an error on `\label(somelabel)`.

So I guess treesitter-latex doesn't support amsmath?

**Comment by yashamon** [comment]
I made a syntax error: It should be curly brackets, sorry. Here is a complete snippet with document class amsart, which may matter also.

\documentclass{amsart}  
\begin{document} 
\begin{equation} \label{somelabel}
  e ^{\pi i}  = -1. 
\end{equation} 
\end {document}

**Comment by lewis6991** [comment]
Ok now we get:

```
class_include [1, 0] - [1, 22]
  path: path [1, 15] - [1, 21]
environment [2, 0] - [6, 15]
  begin: begin [2, 0] - [2, 16]
    name: word [2, 7] - [2, 15]
  child: environment [3, 0] - [5, 14]
    begin: begin [3, 0] - [3, 16]
      name: word [3, 7] - [3, 15]
    child: label_definition [3, 17] - [3, 34]
      name: word [3, 24] - [3, 33]
    child: text [4, 0] - [4, 3]
      word [4, 0] - [4, 1]
      word [4, 2] - [4, 3]
    child: brace_group [4, 3] - [4, 10]
      child: generic_command [4, 4] - [4, 7]
        name: generic_command_name [4, 4] - [4, 7]
      child: text [4, 8] - [4, 9]
        word [4, 8] - [4, 9]
    child: text [4, 11] - [4, 16]
      word [4, 13] - [4, 16]
    end: end [5, 0] - [5, 14]
      name: word [5, 5] - [5, 13]
  end: end [6, 0] - [6, 15]
    name: word [6, 6] - [6, 14]
```

Which has enough information but will require an elaborate query.

**Comment by yashamon** [comment]
I haven't noticed when the change occurred, but it is working perfectly now. At least for the basic environments I tested. So thanks a lot!

**Comment by lewis6991** [comment]
I haven't changed anything

**Comment by yashamon** [comment]
Maybe treesiter did? Anyway I will reopen when the problem resurfaces.

Yasha

**Comment by lewis6991** [comment]
As always, please provide testcase.
