### ISSUE TITLE
plugin doesn't work for me due to the current_syntax check

### ISSUE THREAD

**Issue by emmanueltouzery** [lewis6991/spellsitter.nvim#40]
Hi, I've added spellsitter to my nvim configuration. I'm using packer:

```lua
'lewis6991/spellsitter.nvim'
```

Then I call:

```lua
require('spellsitter').setup()
```

both in my scripts and I also tried calling it later from the editor. It doesn't throw any errors and I see that the plugin is correctly loaded. However the plugin seems to have no effect, it doesn't underline misspelled words as I would expect. I also see no relevant errors in nvim's `:messages`.

I'm using nvim 0.5.1. How could I track down the issue? Or maybe I'm misunderstanding how the plugin should work?

**Comment by lewis6991** [comment]
The plugin is pretty small. Maybe try adding print statements at certain places?

**Comment by emmanueltouzery** [comment]
I have added a couple of prints, I maybe found something, does that help =>

local function buf_enabled(bufnr)

It seems this function always returns false for me.

At first it returns false because of that if:

  if not api.nvim_buf_is_loaded(bufnr) then

But later it returns false because of that if:

  if pcall(api.nvim_buf_get_var, bufnr, 'current_syntax') then

I think this is not normal right? If it's not, any idea why it would come to that, what can I try?

**Comment by emmanueltouzery** [comment]
For what it's worth, I confirmed that if I comment:

```lua
if pcall(api.nvim_buf_get_var, bufnr, 'current_syntax') then
  return false
end
```

Then the plugin seems to work perfectly for me. If I don't comment it, I get no spell checking.

So, I do have a current_syntax defined. For instance, for lua files it's `lua`. for rust files it's `rust`, but it doesn't seem to hamper the plugin, if I manually comment these lines. The plugin works just fine for me, current_syntax or not.

So for myself I commented that if and for now I see no issues. I'd be interested to know why it was added. It seems to be as intended, because the commit message when it was added:
https://github.com/lewis6991/spellsitter.nvim/commit/2351420534e4b66dd4c2768cf7dfccc12780e1ac

is " Disable is b:current_syntax is defined".

**Comment by lewis6991** [comment]
If `current_syntax` is defined, that means the old style syntax has been applied which will include spellchecking. This might get around this:

```lua
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  }
}
```

`additional_vim_regex_highlighting` should be `false` to prevent spellsitter from applying.
