### ISSUE TITLE
Toggle on / off

### ISSUE THREAD

**Issue by lcrockett** [lewis6991/spellsitter.nvim#45]
I was unable to find any leads on the possibility of toggling this plugin on / off. Is this currently supported in any way ?

**Comment by lewis6991** [comment]
`set spell` / `set nospell`

**Comment by lcrockett** [comment]
Cheers on the suggestion, but not entirely what I was looking for as it doesn't produce the desired result. I managed however using the following two snippets, which i've included in a toggle function:

```lua
require('spellsitter').setup {
  enable = { 'none' }
}
```

```lua
require('spellsitter').setup {
  enable = {
    ...
  }
}
```

Thanks anyways !
