### ISSUE TITLE
Error executing lua when opening nvim with no file argument

### ISSUE THREAD

**Issue by yourealwaysbe** [lewis6991/spellsitter.nvim#49]
When opening nvim with no file argument. I.e.

    $ nvim

I receive the error

    (UNKNOWN PLUGIN): Error executing lua: attempt to call a nil value
                                                                      stack traceback:

This is a corrupted line of output and i don't know how to get the actual stack trace.

However, i tracked down the bug to commit 504e89725ec68b163f1a59294031a43b950836dc, and Line 192 of the enabled function in spellsitter.lua

    if not vim.treesitter.highlighter.active[bufnr] then

It looks like vim.treesitter is nil if there is not a file open (though it could also be that displaying the open file just hides the error above). Here is a patch that fixes it, but i'm not sure if it's the "right" solution. Perhaps oddly, returning false if `vim.treesitter` is `nil` results in the same error.

```
diff --git a/lua/spellsitter.lua b/lua/spellsitter.lua
index 55bf1c1..62fcd00 100644
--- a/lua/spellsitter.lua
+++ b/lua/spellsitter.lua
@@ -149,8 +149,10 @@ local function enabled(bufnr, winid)
   if not vim.wo[winid].spell then
     return false
   end
-  if not vim.treesitter.highlighter.active[bufnr] then
-    return false
+  if not vim.treesitter == nil then
+    if not vim.treesitter.highlighter.active[bufnr] then
+      return false
+    end
   end
   local ft = vim.bo[bufnr].filetype
   if config.enable ~= true and not vim.tbl_contains(config.enable, ft) then
```

Version info:

```
$ nvim -v
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

Spellsitter: 2cb4700ed6853c6bfeffadafc3afb43cc45cd09d
nvim-treesitter: 288ef60edde1b5a49c325b0770bdf999ae648a92

**Comment by lewis6991** [comment]
FYI, PR's are better than raw patch files.

**Comment by yourealwaysbe** [comment]
Fair enough, i moved this to https://github.com/lewis6991/spellsitter.nvim/pull/50

(I chose an issue because my fix looks like more of a bodge to me.)
