### ISSUE TITLE
Spellsitter not working anymore with treesitter highlight

### ISSUE THREAD

**Issue by ghost** [lewis6991/spellsitter.nvim#51]
Only comments still working with **enable = true**. Nvim 0.6
**Minimal configuration:**
```
require'nvim-treesitter.configs'.setup {
  -- One of "all", "maintained" (parsers with maintainers), or a list of languages
  ensure_installed = "maintained",

  -- Install languages synchronously (only applied to `ensure_installed`)
  sync_install = false,

  -- List of parsers to ignore installing
  ignore_install = { "javascript" },

  highlight = {
    -- `false` will disable the whole extension
    enable = true,

    -- list of language that will be disabled
    disable = { "c", "rust" },

    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}
require('spellsitter').setup()
```

**Comment by lewis6991** [comment]
This isn't the best bug report.

What are you experiencing and expecting?

**Comment by username551** [comment]
**Expect:** Working spelling with treesitter highlight. But withotu vim_regex - not working. I have set string_literal for rust in queries - for example:

https://user-images.githubusercontent.com/96663334/147830899-589c6847-f76f-4eb1-8185-0e12c57fbba2.mp4

**Comment by username551** [comment]
> This isn't the best bug report.
> 
> What are you experiencing and expecting?

Treesitter highlight hides spell syntax of spellsitter.

**Comment by sbmueller** [comment]
Hi, isn't this a major drawback? The main reason I use this plugin is to be able to use the TreeSitter features with spell checking. Now I have to decide between TreeSitter highlighting XOR spell checking? Is this really intended?

**Comment by lewis6991** [comment]
So spellsitter now uses `set spell` to be enabled/disabled. Normally if you run `set spell` without spellsitter installed you will get spell errors everywhere (including in code). Spellsitter just restricts this so only comments and strings are spell checked.

**Comment by lewis6991** [comment]
>  It doesn't work if I set it in the init.vim, then the code is spellchecked as well (syntax unaware). Is this intended? 

That's not intended. Something funky must be going on. I have `vim.opt.spell = true` in my init.lua and it works fine.

**Comment by sbmueller** [comment]
Output is:
````
No Syntax items defined for this buffer
```

**Comment by lewis6991** [comment]
Ok, well that's the problem. Something is clearing the syntax elements.

For context, when spellsitter attaches to a buffer it should run `syntax cluster Spell contains=NONE` which disables the legacy spellchecker. This can only be cleared with `syntax off` of `syntax clear`, so something in your config must be donig this.

**Comment by lewis6991** [comment]
Try #55
