### ISSUE TITLE
Huge performance degradation

### ISSUE THREAD

**Issue by languitar** [lewis6991/spellsitter.nvim#52]
Since https://github.com/lewis6991/spellsitter.nvim/commit/6035839116af24cecb6b2e4115cdae1e3841d127 I am seeing a huge performance issue with this plugin. When editing a larger YAML file, neovim ends up in a 100 percent CPU loop for ages. I can press Ctrl-C and see a message inline in the edited file that spellsitter was interrupted, but the 100% block starts again when trying to do anything.

This does not happen with the commit before the linked one.

**Comment by lewis6991** [comment]
What version of Neovim are you running. Does your version have `vim.spell.check` available?

**Comment by lewis6991** [comment]
Also does this happen if you reduce the size of your yaml file? Are you able to provide a testcase?

**Comment by languitar** [comment]
> What version of Neovim are you running.

This happens with neovim 0.6.1.

The fragments of the error message on Ctrl-C that I see inside the buffer are:

```
spellsitter: Error executing lua: ...e/pack/packer/start/spellsitter.nvim/lua/spellsitter.lua:126: Error executing lua: Keyboard interrupt
                                                                                                                                          stack traceb
```

> Also does this happen if you reduce the size of your yaml file?

With a reduced file things work reasonably.

> Are you able to provide a testcase?

I haven't yet succeeded. Seems to be some kind of interaction with something else in my config. I'll try to figure out what is causing this.

**Comment by languitar** [comment]
Ah, managed to create a reproduction case:

This is the `init.lua` file:

```lua
vim.cmd [[packadd packer.nvim]]

require('packer').startup(function()
  use 'wbthomason/packer.nvim'

  -- visual
  use { 'nvim-treesitter/nvim-treesitter', run = ':tsupdate' }
  use {
    'lewis6991/spellsitter.nvim',
    config = function()
      require('spellsitter').setup()
    end
  }
end)

-- default spell settings
vim.wo.spell = true
vim.bo.spelllang = 'en,de'

require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "g.",
      node_incremental = ".",
      scope_incremental = ";",
      node_decremental = ",",
    },
  }
}
```

Opening the following file immediately gets stuck in the middle: https://gist.github.com/languitar/0c0bc86a3e00b153ca24db21231f874c

**Comment by languitar** [comment]
Btw, from the position of the error message when pressing ctrl+c it looks like this is triggered by the commented URI in the file.

**Comment by ygworldr** [comment]
At the risk of saying just “me too”, if anyone feels that my setup could be useful, I can provide it. Also, let me know if I can help test something.

**Comment by lewis6991** [comment]
Reproduced and fixed the issue.

This wasn't necessarily a performance issue, but more of an infinite loop occurring, so much worse.

Note can't happen on nvim 0.7 since that uses `vim.spell.check`
