### ISSUE TITLE
Neovim 0.6.1 spell checking not working

### ISSUE THREAD

**Issue by tomleavy** [lewis6991/spellsitter.nvim#54]
I updated to 0.6.1 and I happened to notice that I no longer see any indication of misspellings when writing comments in my rust codebase. This same configuration was working fine with neovim 0.5. I didn't see any errors in the logs, how would I debug to understand what is causing the failure?

**Comment by lewis6991** [comment]
1. Do you have `set spell` set? 
2. What is the output of `:syntax`?

**Comment by lewis6991** [comment]
Also, #55 might fix this.

**Comment by tomleavy** [comment]
That update + `set spell` seems to have fixed it, thanks!
