### ISSUE TITLE
ERROR: Failed to add extmark, lnum=%d pos=%d

### ISSUE THREAD

**Issue by binhtran432k** [lewis6991/spellsitter.nvim#63]
Is there way to disable this log or disable feature relate to this log? This sometimes occurs when I use `[s`, `]s` to go to next misspell. This is very annoying if I have multiple misspell in one line:
![image](https://user-images.githubusercontent.com/26183671/157034347-81758a03-7363-4eb6-b9c2-c1ec70ce2de4.png)

**Comment by lewis6991** [comment]
It means there is a bug somewhere. Can you provide a way to reproduce this?

**Comment by lewis6991** [comment]
No response in over a month. Closing.
