### ISSUE TITLE
Plugin doesn't check spelling even in strings

### ISSUE THREAD

**Issue by timsofteng** [lewis6991/spellsitter.nvim#64]
Hello.
I've guessed the goal of this plugin is to improve default nvim's spellchecking add prevent some spelling for keywords as `const` or something like that.
But it even doesn't highlight words in string.
Here is `.tsx` example:

![image](https://user-images.githubusercontent.com/51912173/163564320-6dde3a47-2f90-4a17-be67-4c61daee779d.png)

**Comment by lewis6991** [comment]
What is spellchecked in defined by query files here https://github.com/lewis6991/spellsitter.nvim/tree/master/queries. Each query is different for each language.

**Comment by timsofteng** [comment]
Got it. 
If i get correctly no query for js or ts files...
Why no checking for variables and functions name even for existed queries?

**Comment by lewis6991** [comment]
If there are no query files then only comments are spell checked. See: https://github.com/lewis6991/spellsitter.nvim/blob/f84e7a31c516f2a9cb857a02e4b551b009a81afb/lua/spellsitter.lua#L159-L176

**Comment by timsofteng** [comment]
> If there are no query files then only comments are spell checked. See:
> 
> https://github.com/lewis6991/spellsitter.nvim/blob/f84e7a31c516f2a9cb857a02e4b551b009a81afb/lua/spellsitter.lua#L159-L176

I understand. My question is why spell checking not implemented to check variabales and functions names even for existed queries?

**Comment by lewis6991** [comment]
Because you wouldn't want to spellcheck them.

**Comment by timsofteng** [comment]
> Because you wouldn't want to spellcheck them.

Hm. Why not? This is user responsibility and outside of lsp-checker. In my opinion it would be cool to have ability to check spelling in names of functions and variables.

**Comment by lewis6991** [comment]
Sorry, out of scope for this plugin. If you want to spellcheck everything, then simply uninstall spellsitter and all function and variable names will be spell checked.

The **ONLY** purpose of this plugin is to achieve the same level of spellchecking for treesitter enabled buffers as buffers with `syntax on`, as the README illustrates.

**Comment by timsofteng** [comment]
Thanks. Do you know any way to achieve my goal?
I want to have spellcheking for only specific things as names of variables, path, comments and strings.

**Comment by lewis6991** [comment]
Implement your own spell queries that capture the groups you want to check.
