### ISSUE TITLE
How can I disable it in the terminal?

### ISSUE THREAD

**Issue by Aqashir** [lewis6991/spellsitter.nvim#65]
Hello, how are you? I hope that you are doing well!!
can someone please tell me how to disable spell checking in the terminal? I tried using this 'vim.cmd[[set nospell filetype=toggleterm]]', but it will disable this plugin

**Comment by lewis6991** [comment]
Pretty sure this is unrelated to this plugin.

**Comment by feslima** [comment]
@Aqashir This might be a bit late but, for anyone who needs something similar, you must handle this with an autocmd and a local set. That is, simply put this somewhere in you config (in my case, I use neovim):

```lua
vim.api.nvim_create_autocmd("TermOpen", { pattern = "term://*", command = "setlocal nospell" })
```
This will disable the builtin spell check for any terminal. If you want to disable this only for toggleterm, just set the `pattern = "term://*toggleterm#*"` and you are good to go.
