### ISSUE TITLE
Blacklist for buffertypes

### ISSUE THREAD

**Issue by yavko** [lewis6991/spellsitter.nvim#66]
Instead of a whitelist could there be a blacklist?

**Comment by jamestrew** [comment]
I'm also thinking the ability to blacklist would be nice.
Maybe following the path of how `nvim-treesitter.setup` handles whitelist and blacklist.

From `:h nvim-treesitter-modules`

```lua
  require'nvim-treesitter.configs'.setup {
    highlight = {
      enable = true,
      disable = { "cpp", "lua" },
    },
  }

-- disable can also be a function
  require'nvim-treesitter.configs'.setup {
    highlight = {
      enable = true,
      disable = function(lang, bufnr) -- Disable in large C++ buffers
        return lang == "cpp" and vim.api.nvim_buf_line_count(bufnr) > 50000
      end,
    },
  }
```

I'll be happy to put together a PR if this seems like a good idea.

**Comment by lewis6991** [comment]
Sounds good to me

**Comment by jamestrew** [comment]
To clarify, I'm guessing that to blacklist a filetype, that means to disable spellsitter as well as set `nospell`. 

I don't think it makes sense to disable spellsitter but leave spellchecking on. Then you'd have to also write your own autocmds to `setlocal nospell` for the same filetypes again if you wanted no spellchecking whatsoever.

**Comment by lewis6991** [comment]
Yeah, this makes sense. I should have realized this myself.

You can implement an effective exclude list by simply adding a `FileType` autocmd to set `setlocal nospell`.
