### ISSUE TITLE
spell sitter overrides tree sitter's comment parser

### ISSUE THREAD

**Issue by gegoune** [lewis6991/spellsitter.nvim#7]
Hi, that looks really great, thanks! And given how amazing gitsigns is I am sure this plugin will get widely adopted too.

I have just noticed that it overrides highlighting for tree sitter's comment parser, stuff like `TODO:, FIXME:` etc.

Could probably add them to dictionary as valid words, but perhaps that exposes some issue with how highlights are prioritised so thought I might  mention it.

Thanks!

**Comment by lewis6991** [comment]
The idea of this plugin is that it just enables the built-in spellchecker to sensibly work on TS-enabled buffers, so this issue is only relevant if the regex-syntax highlighting does something different to this plugin.

Otherwise, the solution would be to just add TODO, FIXME as valid words.
