### ISSUE TITLE
Spell check errors in `ts` and `js` files

### ISSUE THREAD

**Issue by askfiy** [lewis6991/spellsitter.nvim#72]
Well, this question was asked in `treesitter`, I'm sure I have installed `spellsitter` plugin, but the problem persists, can you help me?

I'm sure `spellsitter` is in effect.

[#3019](https://github.com/nvim-treesitter/nvim-treesitter/issues/3019)

**Comment by lewis6991** [comment]
When raising issues in an issue tracker, please provide full context and reproducible steps. Otherwise you are wasting people's time.

Whilst I'm happy to provide some support, this isn't a support forum.

**Comment by askfiy** [comment]
Well, I noticed that it doesn't seem to support ts and js, maybe we should update the README to let everyone know which languages it currently supports.

**Comment by lewis6991** [comment]
It supports all languages nvim-treesitter supports but to varying degrees. If there aren't any specific queries for a particular language, then only comments are spellchecked, which is what you want 90% of the time. People who use particular languages and want richer spellchecking have contributed queries.
