### ISSUE TITLE
Markdown error (query: invalid node type at position)

### ISSUE THREAD

**Issue by Integralist** [lewis6991/spellsitter.nvim#78]
I raised the following issue in treesitter repo but was redirected here:
https://github.com/nvim-treesitter/nvim-treesitter/issues/3108#event-6922536680

**Comment by daliusd** [comment]
I experience this problem with markdown files as well. Neovim dev newest version. Otherwise spellsitter works fine.

**Comment by daliusd** [comment]
OK. This is fixed with this PR https://github.com/lewis6991/spellsitter.nvim/issues/75

**Comment by Integralist** [comment]
Oh great. So if I use the master branch this should be fixed then, right?

**Comment by daliusd** [comment]
Feel free to close this one :)
