### ISSUE TITLE
Not beeing able to clear the spell highlights

### ISSUE THREAD

**Issue by Sh3Rm4n** [lewis6991/spellsitter.nvim#9]
If I understand it correctly, spellsitter applies its own highlight, when activating spell via `set spell` and disables the builtin spell directly afterwards:

https://github.com/lewis6991/spellsitter.nvim/blob/58af4c1ebfe3690ac53cb556e439bbd8b997c8ea/lua/spellsitter.lua#L155-L160

This applies the highlights on the buffer. But the normal workflow with the built-in spell option is to enable it, to see the highlights, and disable it to clear the `SpellBad` highlights. 

Is there a way to clear the highlights? Preferably with `set nospell` but if not feasible, with an extra command? If you point me towards the right direction, I could give it a try.

**Comment by lewis6991** [comment]
`set nospell`is required to prevent the built-in spellchecker applying normally. I don't know of any built-in options we can work this off. Maybe the simplest option is to provide a command to enable/disable spellsitter.

The plugin is pretty small so should be easy to approach for modifications. You just need to be aware with how some of the API functions it depends on work. E.g. `nvim_set_decoration_provider`

**Comment by lewis6991** [comment]
This should be fixed with 42cc285424398a2d07b5fd62e7c01e2209441fa1 as spellsitter now respects `set spell`.

**Comment by Sh3Rm4n** [comment]
Nice! Thank you very much for your work 🙏
